IMAGES ?= base paper waterfall

.PHONY: build
build:
	cd base && make build
	cd paper && make build
	cd waterfall && make build

.PHONY: push
push:
	cd base && make push
	cd paper && make push
	cd waterfall && make push
