apiVersion: v1
kind: ConfigMap
data:
  eula.txt: |
  {{- index .Values.config "eula.txt" | nindent 4 }}

  base_plugins_install_list.txt: |
  {{- (index .Values.config "base_plugins_install_list.txt" | default "") | nindent 4 }}

  plugins_install_list.txt: |
  {{- (index .Values.config "plugins_install_list.txt" | default "") | nindent 4 }}
metadata:
  name: {{ include "paper.fullname" . }}
  labels:
    {{- include "paper.labels" . | nindent 4 }}
