apiVersion: v1
kind: Service
metadata:
  name: {{ include "paper.fullname" . }}
  labels:
    {{- include "paper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: paper
      protocol: TCP
      name: server
  selector:
    {{- include "paper.selectorLabels" . | nindent 4 }}
