apiVersion: v1
kind: ConfigMap
data:
  base_plugins_install_list.txt: |
  {{- (index .Values.config "base_plugins_install_list.txt" | default "") | nindent 4 }}

  plugins_install_list.txt: |
  {{- (index .Values.config "plugins_install_list.txt" | default "") | nindent 4 }}
metadata:
  name: {{ include "waterfall.fullname" . }}
  labels:
    {{- include "waterfall.labels" . | nindent 4 }}
