{{- if and .Values.serviceMonitor .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "waterfall.fullname" . }}
  labels:
    {{- include "waterfall.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 15s
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "waterfall.selectorLabels" . | nindent 6 }}
{{- end }}
