name: container-images-build
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: docker login to quay.io registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin quay.io
      - name: Build
        if: success()
        run: make -C container/ build push BUILDAH_LAYERS=false
