name: container-images-build
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to quay registry
        uses: actions-hub/docker/login@v1.0.2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: quay.io
      - name: Build
        if: success()
        run: make -C container/ build push BUILDAH_LAYERS=false
