name: daily-update
on:
  schedule:
    - cron:  '20 10 * * *'
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run Paper MC Version Checker and Updater
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./scripts/update-papermc-versions.sh
