name: daily-update
on:
  #schedule:
  #  - cron:  '20 10 * * *'
  push:
    branches:
      - test
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - name: Run Paper MC Version Checker and Updater
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          ./scripts/update-papermc-versions.sh
